apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cawa-app
spec:
  selector:
    matchLabels:
      app: cawa-app
  replicas: 1
  template:
    metadata:
      labels:
        app:  cawa-app
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  cawa-app
        image:  parkar05/cawa-app:latest
        imagePullPolicy: Always